### ISSUE TITLE
Question about the output of simulate

### ISSUE THREAD

**Issue by gitlaxy** [alchemyst/Dynamics-and-Control#18]
Hi,

The result of [simulate](https://github.com/alchemyst/Dynamics-and-Control/blob/92bdbaf507691c14174f53bfc8aa1bbdddadec14/tbcontrol/blocksim.py#L293) is in the time domain already or still in the Laplace (frequency) domain?

Thanks

**Comment by alchemyst** [comment]
@gitlaxy It is in the time domain. Specifically, it returns the values of each of the variables at the simulation sampling intervals (so it's not returning a symbolic solution, but rather a numeric one).
