### ISSUE TITLE
Cannot import tbcontrol

### ISSUE THREAD

**Issue by ingodahn** [alchemyst/Dynamics-and-Control#20]
In Cheatsheet I get the following error on Binder:
![image](https://user-images.githubusercontent.com/3258024/148952583-e1c8ce86-4a46-4eac-b547-53bcd5d913d4.png)

On CoCalc I get a similar error after importing the complete repo.

Is there a way to import tbcontrol directly from a location on Github?

**Comment by alchemyst** [comment]
Thank you for the report. I've added tbcontrol to our dependencies in `environment.yml`. I can verify that the cell above runs without error for me on binder now. I'm not sure about CoCalc, but note that tbcontrol is on PyPI, so you can just `pip install tbcontrol` to get it.
