### ISSUE TITLE
Link typo in Closed loop stability → Routh array

### ISSUE THREAD

**Issue by pierre-haessig** [alchemyst/Dynamics-and-Control#21]
Hi!

I just came across your great collection of notebooks (almost a textbook in fact). While reading, I noticed a typo in the last link of 

https://dynamics-and-control.readthedocs.io/en/latest/2_Control/2_Laplace_domain_analysis_of_control_systems/Stability%20analysis.html

> How can we determine stability without calculating the roots? See the [next notebook](https://dynamics-and-control.readthedocs.io/en/latest/2_Control/2_Laplace_domain_analysis_of_control_systems/Sympy%20Routh%20Array.ipynb).

This link is broken because it should be point to `SymPy Routh Array.html` (capital case in Sympy + extension). I guess that for the extension there is a tradeoff between having it work in the html export versus in the actual collection of notebook files.

**Comment by alchemyst** [comment]
Thank you for reporting this. I haven't looked at this repository in a while and I will try to at least fix the notebook link.
