### ISSUE TITLE
How to Download the Whole Dynamics and Control Book in PDF?

### ISSUE THREAD

**Issue by glanzkaiser** [alchemyst/Dynamics-and-Control#22]
Hi all,

First of all when I try to download the whole book I can't get the pdf. I do not want the .ipynb separately nor the html,

I prefer one pdf that contains all chapters in DYnamics and Control here:
https://dynamics-and-control.readthedocs.io/en/latest/index.html

I want to print it into a book so I can read it without internet. Thanks before. It is a very helpful to all of us want to learn.

**Comment by alchemyst** [comment]
The default settings for readthedocs would appear to be to build a PDF. I believe that this was not working with unicode variable names the last time I checked. I will put in some time to try to get it to build correctly.

**Comment by glanzkaiser** [comment]
I tried to save pdf from Print the page at the browser, there are some issues:
1. The plot result sometimes outline the text below
2. The pagebreak is not tidy as what pdf book should

Here is the one that I downloaded one by one and then merge it. If the contributor here can make the official pdf it will be great. Because printing it into book is far better, it can be read over and over again without damaging eyes too much like reading from computer or LCD display.

[Dynamics and Control with Jupyter Notebooks.pdf](https://github.com/alchemyst/Dynamics-and-Control/files/12582330/Dynamics.and.Control.with.Jupyter.Notebooks.pdf)

**Comment by alchemyst** [comment]
I have enabled and corrected the [PDF build](https://dynamics-and-control.readthedocs.io/_/downloads/en/latest/pdf/). I note that there is still some work to be done to get this to render well, but I'm closing this ticket now that the artefact is actually there.
