### ISSUE TITLE
laplace_transform has changed a lot

### ISSUE THREAD

**Issue by hanspi42** [alchemyst/Dynamics-and-Control#24]
Just wanted to let you know: the Laplace transform got major updates in SymPy 1.11 and 1.12 (and is still being updated for 1.13).

In `Laplace Transforms.ipynb`, you have an example *More complicated inverses* which shows hiow sometimes `.apart()` might help, but that example does not work anymore since `laplace_transform` will use `.apart()` by itself if appropriate.

**Comment by alchemyst** [comment]
I have reworded this notebook in f0803e6bc4207e37ad7bdc240d6cf17323759767
