### ISSUE TITLE
Citation

### ISSUE THREAD

**Issue by llandsmeer** [alchemyst/Dynamics-and-Control#27]
Dear author,

I'm using stability analysis from the tbcontrol package in a paper draft, is there a way how you prefer to be cited?

Thanks,
Lennart

**Comment by alchemyst** [comment]
Hello Lennart.

Thank you for reaching out to cite the package. I have added a CITATION.cff file to the package, which will allow you to get citation information from GitHub on the [main page](https://github.com/alchemyst/Dynamics-and-Control) by clicking "Cite this repository" on the right hand side.
